# Generated by Django 5.0.6 on 2025-07-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_media_alter_report_options_remove_report_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
