# Generated by Django 5.0.6 on 2025-08-11 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_safetyzone_alter_report_report_type_hospital_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.DeleteModel(
            name='PoliceStation',
        ),
        migrations.DeleteModel(
            name='SafetyZone',
        ),
    ]
