# Generated by Django 5.0.6 on 2025-08-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_delete_hospital_delete_policestation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('infrastructure', 'Infrastructure Issue'), ('harassment', 'Harassment'), ('crime', 'Crime'), ('safety', 'Safety Concern'), ('other', 'Other')], max_length=20),
        ),
    ]
