# Generated by Django 5.0.6 on 2025-08-08 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='emergency_type',
            field=models.CharField(default='general_emergency', max_length=50),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='is_streaming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='stream_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SOSLocationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sos_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to='sos.sosalert')),
            ],
        ),
        migrations.CreateModel(
            name='SOSVideoFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='sos_videos/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sent_to_police', models.BooleanField(default=True)),
                ('sos_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_feeds', to='sos.sosalert')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerted_at', models.DateTimeField(auto_now_add=True)),
                ('responded', models.BooleanField(default=False)),
                ('response_time', models.DateTimeField(blank=True, null=True)),
                ('sos_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sos.sosalert')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sos.volunteer')),
            ],
        ),
    ]
