# Generated by Django 5.0.6 on 2025-08-17 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0003_sosalert_emergency_type_sosalert_is_streaming_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteeralert',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteeralert',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteeralert',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteeralert',
            name='sos_alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_alerts', to='sos.sosalert'),
        ),
        migrations.AlterField(
            model_name='volunteeralert',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='sos.volunteer'),
        ),
        migrations.AlterUniqueTogether(
            name='volunteeralert',
            unique_together={('sos_alert', 'volunteer')},
        ),
    ]
