# Generated by Django 5.0.6 on 2025-08-17 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0004_sosalert_description_volunteeralert_distance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sosvideofeed',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='sosalert',
            name='camera_feed_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='total_video_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='video_chunks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sosvideofeed',
            name='chunk_sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sosvideofeed',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sosvideofeed',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sosvideofeed',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sosvideofeed',
            name='viewed_by_police',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PoliceVideoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('viewing_duration', models.IntegerField(blank=True, null=True)),
                ('police_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police_views', to='sos.sosvideofeed')),
            ],
            options={
                'unique_together': {('video_feed', 'police_officer')},
            },
        ),
    ]
