# Generated by Django 5.0.6 on 2025-08-19 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0005_alter_sosvideofeed_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sosvideofeed',
            name='viewed_at',
        ),
        migrations.RemoveField(
            model_name='sosvideofeed',
            name='viewed_by_police',
        ),
        migrations.AddField(
            model_name='sosvideofeed',
            name='emergency_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sosvideofeed',
            name='sos_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_feeds', to='sos.sosalert'),
        ),
        migrations.AddIndex(
            model_name='sosvideofeed',
            index=models.Index(fields=['emergency_id', '-timestamp'], name='sos_sosvide_emergen_e62a57_idx'),
        ),
    ]
