# Generated by Django 5.0.6 on 2025-08-19 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('safety', '0001_initial'),
        ('sos', '0005_alter_sosvideofeed_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('safety', 'Safety Advisory'), ('traffic', 'Traffic Update'), ('emergency', 'Emergency Notice'), ('community', 'Community Notice')], default='community', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by_officer', models.ForeignKey(limit_choices_to={'role': 'police'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('issued_by_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safety.policestation')),
            ],
        ),
        migrations.CreateModel(
            name='PatrolTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=20, unique=True)),
                ('members_count', models.IntegerField(default=2)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrol_teams', to='safety.policestation')),
                ('team_leader', models.ForeignKey(limit_choices_to={'role': 'police'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SOSResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Team Assigned'), ('dispatched', 'Team Dispatched'), ('arrived', 'Arrived on Scene'), ('resolved', 'Resolved')], default='assigned', max_length=20)),
                ('response_time', models.DurationField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police.patrolteam')),
                ('sos_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police_responses', to='sos.sosalert')),
            ],
        ),
    ]
