# Generated by Django 5.0.6 on 2025-08-21 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patrolteam',
            name='members',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'police'}, related_name='patrol_teams_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
