# Generated by Django 5.0.6 on 2025-08-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_volunteer',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('volunteer', 'Volunteer'), ('police', 'Police'), ('municipality', 'Municipality'), ('city admin', 'City Admin'), ('state admin', 'State Admin')], default='Citizen', max_length=20),
        ),
    ]
