# Generated by Django 5.0.6 on 2025-08-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_address_user_bio_user_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='occupation',
        ),
    ]
