# Generated by Django 5.0.6 on 2025-08-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_address_remove_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('volunteer', 'Volunteer'), ('police', 'Police'), ('municipality', 'Municipality'), ('city admin', 'City Admin'), ('state admin', 'State Admin'), ('admin', 'Admin')], default='citizen', max_length=20),
        ),
    ]
