# Generated by Django 5.0.6 on 2025-08-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('volunteer', 'Volunteer'), ('police', 'Police'), ('municipality', 'Municipality'), ('government', 'Government'), ('admin', 'Admin')], default='citizen', max_length=20),
        ),
    ]
