# Generated by Django 5.0.6 on 2025-08-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_volunteerapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='motivation',
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
