# Generated by Django 5.0.6 on 2025-08-21 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
        ('users', '0011_remove_volunteerapplication_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='police_station',
            field=models.ForeignKey(blank=True, help_text='Police Station for police role users', null=True, on_delete=django.db.models.deletion.SET_NULL, to='safety.policestation'),
        ),
    ]
